language: cpp
before_script:
- sudo apt-get update -qq
- sudo apt-get install libgtest-dev -y
- cd /usr/src/gtest
- sudo env "PATH=$PATH" cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd "${TRAVIS_BUILD_DIR}"
- sudo apt-get install g++-5
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package